# This file is moved to the root directory before building the image

/node_modules
*.log
.DS_Store
.env
.env.*
/.git
/.github
/.claude
/.storybook
/.vscode
/.cache
/coverage
/playwright-report
/test-results
/tests
/tests/prisma
/server-build
/public/build
/build
/.react-router
/other/cache.db
*.local.*
