name: CI

on:
  push: # every branch
  pull_request: # every PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:icons
      - run: npm run lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:icons
      - run: npm run typecheck --if-present

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: cp .env.example .env
      - run: npm run build:icons
      - run: npm run test -- --coverage

  playwright:
    name: 🎭 Playwright
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - run: cp .env.example .env
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test:e2e:install
      - run: npx prisma migrate deploy
      - id: db-cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: prisma/data.db
          key: db-cache-schema_${{
            hashFiles('prisma/schema.prisma')}}-migrations_${{
            hashFiles('prisma/migrations/*/migration.sql') }}
      - run: npx prisma db seed
        if: steps.db-cache.outputs.cache-hit != 'true'
        env:
          MINIMAL_SEED: true
      - run: npm run build
      - run: npx playwright test
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
