name: CI

on:
  push: # every branch
  pull_request: # every PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:icons
      - run: npm run lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:icons
      - run: npm run typecheck --if-present

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: cp .env.example .env
      - run: npm run build:icons
      - run: npm run test -- --coverage

  playwright:
    name: 🎭 Playwright
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - run: cp .env.example .env
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test:e2e:install
      - run: npx prisma migrate deploy
      - id: db-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: prisma/data.db
          key: db-cache-schema_${{
            hashFiles('prisma/schema.prisma')}}-migrations_${{
            hashFiles('prisma/migrations/*/migration.sql') }}
      - run: npx prisma db seed
        if: steps.db-cache.outputs.cache-hit != 'true'
        env:
          MINIMAL_SEED: true
      - run: npm run build
      - run: npx playwright test
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
